ALTER TABLE products ADD COLUMN IF NOT EXISTS del_flag BOOLEAN DEFAULT FALSE;
ALTER TABLE products ALTER COLUMN del_flag SET NOT NULL;

ALTER TABLE categories ADD COLUMN IF NOT EXISTS del_flag BOOLEAN DEFAULT FALSE;
ALTER TABLE categories ALTER COLUMN del_flag SET NOT NULL;